import type{Scene}from'./types';

export const scenes:Scene[]=[
 {id:'bath',caseNo:'307',title:{zh:'浴缸异常',en:'BATHTUB ANOMALY'},setup:{zh:'凌晨 02:17。住客说浴缸的排水口正在播放海浪声。',en:'02:17 AM. THE GUEST SAYS OCEAN WAVES ARE COMING THROUGH THE BATHTUB DRAIN.'},question:{zh:'浴缸里传来海浪声。怎么处理？',en:'OCEAN WAVES ARE COMING FROM THE TUB. WHAT NOW?'},alt:{zh:'Mara 与住客查看普通浴缸',en:'Mara and a guest inspect an ordinary bathtub'},start:'./generated/hotel_start.webp',outcomes:[
  {id:'plug',label:{zh:'塞住排水口',en:'SEAL THE DRAIN'},title:{zh:'海洋拒绝退房',en:'THE OCEAN REFUSED TO CHECK OUT'},detail:{zh:'黄铜塞只让海水更生气。三条热带鱼现已登记为长期住客。',en:'The brass plug only made the ocean angrier. Three tropical fish are now long-term guests.'},success:false,video:'./generated/plug_cinema.mp4',end:'./generated/plug_end.webp',captions:{zh:['排水口封闭指令已确认。','水压正在礼貌地上升。','海浪与三位鱼类住客抵达。','307号房拒绝保持干燥。'],en:['Drain seal confirmed.','Water pressure is rising politely.','A wave and three fish guests arrive.','Room 307 declines to stay dry.']}},
  {id:'maintenance',label:{zh:'呼叫夜间维修',en:'CALL NIGHT MAINTENANCE'},title:{zh:'海底维修已送达',en:'UNDERSEA MAINTENANCE DELIVERED'},detail:{zh:'服务铃召来无人潜水维修箱。它没有填写工单，也没有留下小费。',en:'The bell summoned an unmanned deep-sea repair kit. It filed no work order and left no tip.'},success:false,video:'./generated/maintenance_cinema.mp4',end:'./generated/maintenance_end.webp',captions:{zh:['夜间维修铃已响一次。','浴缸正在处理工单。','无人潜水维修箱浮出水面。','维修部门拒绝透露所在楼层。'],en:['The night bell rings once.','The bathtub processes the ticket.','An unmanned dive kit surfaces.','Maintenance declines to name its floor.']}},
  {id:'suite',label:{zh:'升级为海景套房',en:'UPGRADE TO OCEAN SUITE'},title:{zh:'首位八腕贵宾入住',en:'FIRST EIGHT-ARMED VIP CHECKED IN'},detail:{zh:'章鱼接受房卡，并礼貌地把客房餐盘还给酒店。下一步是办理入住。',en:'The octopus accepts the keycard and politely returns the room-service tray. Check-in is next.'},success:true,video:'./generated/suite_cinema.mp4',end:'./generated/suite_end.webp',captions:{zh:['海景升级已获批准。','浴缸正在联系住客。','八腕贵宾接过房卡。','客房服务进入正式流程。'],en:['Ocean-suite upgrade approved.','The bathtub contacts its guest.','An eight-armed VIP accepts the key.','Room service enters official procedure.']}}
 ]},
 {id:'checkin',caseNo:'308',title:{zh:'贵宾没有证件',en:'VIP HAS NO IDENTIFICATION'},setup:{zh:'章鱼来到前台。它没有证件，只伸出一只触手要求入住。',en:'THE OCTOPUS REACHES RECEPTION. IT HAS NO ID, ONLY ONE TENTACLE REQUESTING CHECK-IN.'},question:{zh:'章鱼没有证件。怎么给它办入住？',en:'THE OCTOPUS HAS NO ID. HOW DO YOU CHECK IT IN?'},alt:{zh:'Mara 在酒店前台接待章鱼住客',en:'Mara receives the octopus guest at the hotel desk'},start:'./generated/scene2_start.webp',outcomes:[
  {id:'passport',label:{zh:'请它出示护照',en:'ASK FOR A PASSPORT'},title:{zh:'吸盘被认作官方印章',en:'SUCTION CUP ACCEPTED AS OFFICIAL STAMP'},detail:{zh:'章鱼在空白护照上留下一个巨大吸盘印。系统仍然找不到出生日期。',en:'The octopus leaves one enormous suction mark on a blank passport. The system still cannot find a birth date.'},success:false,video:'./generated/passport_cinema.mp4',end:'./generated/passport_end.webp',captions:{zh:['Mara 提出证件要求。','章鱼接受身份核验。','一只吸盘完成盖章。','护照更湿了，信息没有增加。'],en:['Mara requests identification.','The octopus accepts verification.','One suction cup completes the stamp.','The passport is wetter, not clearer.']}},
  {id:'charge-eight',label:{zh:'按八位住客收费',en:'CHARGE FOR EIGHT GUESTS'},title:{zh:'账单长过了章鱼',en:'THE BILL OUTGREW THE OCTOPUS'},detail:{zh:'前台摆出八把钥匙和一张落到地面的账单。贵宾第一次考虑取消预订。',en:'Reception produces eight keys and a bill that reaches the floor. The VIP considers cancelling.'},success:false,video:'./generated/charge-eight_cinema.mp4',end:'./generated/charge-eight_end.webp',captions:{zh:['系统按八位住客计费。','八把房间钥匙依次摆好。','账单开始越过柜台。','章鱼提出价格异议。'],en:['The system charges eight guests.','Eight room keys line up.','The bill crosses the counter.','The octopus disputes the rate.']}},
  {id:'eight-signatures',label:{zh:'让八只触手分别签名',en:'LET EVERY ARM SIGN'},title:{zh:'八份签名全部有效',en:'ALL EIGHT SIGNATURES VALID'},detail:{zh:'八只触手各签一张空白登记卡。Mara 发出八张房卡，入住程序正式通过。',en:'Eight tentacles sign eight blank registration cards. Mara issues eight keys and approves check-in.'},success:true,video:'./generated/eight-signatures_cinema.mp4',end:'./generated/eight-signatures_end.webp',captions:{zh:['Mara 把一张表格拆成八份。','其余七只触手抵达前台。','八支笔同时完成签名。','入住程序正式通过。'],en:['Mara divides one form into eight.','Seven more tentacles reach the desk.','Eight pens sign at once.','Check-in is officially approved.']}}
 ]},
 {id:'bells',caseNo:'309',title:{zh:'八只手同时呼叫服务',en:'EIGHT SERVICE CALLS AT ONCE'},setup:{zh:'入住完成。八只触手同时按响客房服务铃。',en:'CHECK-IN IS COMPLETE. EIGHT TENTACLES RING FOR ROOM SERVICE AT ONCE.'},question:{zh:'八只触手同时按铃。最后怎么办？',en:'EIGHT ARMS RING AT ONCE. FINAL RESPONSE?'},alt:{zh:'八只章鱼触手在酒店前台同时登记',en:'Eight octopus tentacles registered at the hotel desk'},start:'./generated/scene3_start.webp',outcomes:[
  {id:'unplug',label:{zh:'拔掉电话线',en:'UNPLUG THE PHONE'},title:{zh:'电话停了，铃没有',en:'PHONE STOPPED. BELLS DID NOT.'},detail:{zh:'Mara 拔掉电话线，八只触手立即改按黄铜服务铃。住客开始捂耳朵。',en:'Mara unplugs the phone. Eight tentacles immediately switch to brass service bells.'},success:false,video:'./generated/unplug_cinema.mp4',end:'./generated/unplug_end.webp',captions:{zh:['电话线已正式拔除。','前台安静了半秒。','八只触手找到八个服务铃。','夜班噪声改为纯机械。'],en:['The phone is officially unplugged.','Reception is quiet for half a second.','Eight arms find eight service bells.','Night noise becomes fully mechanical.']}},
  {id:'eight-breakfasts',label:{zh:'一次送八份早餐',en:'DELIVER EIGHT BREAKFASTS'},title:{zh:'早餐塔达到危险高度',en:'BREAKFAST TOWER REACHED DANGER HEIGHT'},detail:{zh:'八个银色餐盘组成一座摇晃的早餐塔。最上面的面包先办理了退房。',en:'Eight silver trays form a leaning breakfast tower. The top bread roll checks out first.'},success:false,video:'./generated/eight-breakfasts_cinema.mp4',end:'./generated/eight-breakfasts_end.webp',captions:{zh:['厨房确认八份早餐。','银色餐盘开始叠高。','Mara 接住第七层。','最上面的面包提前退房。'],en:['The kitchen confirms eight breakfasts.','Silver trays begin stacking.','Mara catches level seven.','The top bread roll checks out early.']}},
  {id:'night-manager',label:{zh:'请它接管夜班前台',en:'PUT IT ON THE NIGHT DESK'},title:{zh:'夜班效率提升八倍',en:'NIGHT DESK EFFICIENCY ×8'},detail:{zh:'章鱼同时处理电话、房卡、餐盘和服务铃。Mara 拿起外套下班，307号房的海水仍在流。',en:'The octopus handles phone, keys, trays and bells at once. Mara clocks out while room 307 keeps leaking.'},success:true,video:'./generated/night-manager_cinema.mp4',end:'./generated/night-manager_end.webp',captions:{zh:['Mara 提交夜班任命。','八只触手接管前台设备。','电话、房卡和餐盘同时处理。','Mara 下班。海水继续上班。'],en:['Mara files a night-shift appointment.','Eight arms take over reception.','Phones, keys and trays move at once.','Mara clocks out. The ocean does not.']}}
 ]}
];

export const HOTEL_VIDEOS=scenes.flatMap(scene=>scene.outcomes.map(outcome=>outcome.video));
