import{useEffect,useMemo,useState}from'react';import{endings}from'./data';import{ArrowIcon,Footage,HOTEL_VIDEOS,HotelStill,SoundIcon}from'./components';import{detectLocale,t}from'./i18n';import{beat as playBeat,choose as playChoose,power}from'./utils/sounds';import type{EndingId,Phase}from'./types';import'./MidnightHotelLedger.less';
const STORE='midnight_hotel_ledger_reports_v1';
export default function MidnightHotelLedger(){const locale=useMemo(detectLocale,[]),[phase,setPhase]=useState<Phase>('cover'),[selected,setSelected]=useState<EndingId|null>(null),[beat,setBeat]=useState(0),[sound,setSound]=useState(true),[isNew,setIsNew]=useState(false),[found,setFound]=useState<Set<EndingId>>(()=>{try{return new Set(JSON.parse(localStorage.getItem(STORE)||'[]'))}catch{return new Set()}});
 useEffect(()=>{const calc=()=>{const width=document.documentElement.clientWidth;const scale=width<=520?width/390:1;document.documentElement.style.setProperty('--mhl-scale',String(scale));document.documentElement.style.setProperty('--mhl-height',`${844*scale}px`)};calc();addEventListener('resize',calc);return()=>removeEventListener('resize',calc)},[]);
 useEffect(()=>{window.scrollTo(0,0)},[phase]);
 useEffect(()=>{if(phase==='cover'||phase==='incident'){const loaders=HOTEL_VIDEOS.map(src=>{const v=document.createElement('video');v.preload='auto';v.src=src;return v});return()=>loaders.forEach(v=>{v.removeAttribute('src');v.load()})}},[phase]);
 useEffect(()=>{if(phase!=='footage'||!selected)return;const points=[[650,1],[2200,2],[4100,3],[5200,4]]as const;const timers=points.map(([ms,b])=>window.setTimeout(()=>{setBeat(b);if(sound)playBeat(selected,b);if(b===4){setFound(old=>{const next=new Set(old);next.add(selected);localStorage.setItem(STORE,JSON.stringify([...next]));return next});setPhase('report')}},ms));return()=>timers.forEach(clearTimeout)},[phase,selected,sound]);
 useEffect(()=>{const fn=(e:KeyboardEvent)=>{if(e.key.toLowerCase()==='m')setSound(v=>!v);else if(e.key==='Enter'&&(phase==='cover'||phase==='report'))phase==='cover'?boot():review();else if(phase==='incident'&&['1','2','3'].includes(e.key))select(endings[Number(e.key)-1].id)};addEventListener('keydown',fn);return()=>removeEventListener('keydown',fn)});
 const boot=()=>{setPhase('incident');if(sound)power()},select=(id:EndingId)=>{if(phase!=='incident')return;setIsNew(!found.has(id));setSelected(id);setBeat(0);setPhase('footage');if(sound)playChoose()},review=()=>{setSelected(null);setBeat(0);setPhase('incident')},item=selected?endings.find(e=>e.id===selected)!:null;
 return <main className="mhl-shell"><article className={`mhl-terminal mhl-terminal--${phase}`}><header><div className="mhl-brand"><span>THE AUBERGE NOCTURNE</span><strong>{t(locale,'hotel')}</strong></div><div className="mhl-status"><i/><span>NIGHT<br/>DESK</span></div><div className="mhl-progress"><small>{t(locale,'filed')}</small><b>{found.size}/3</b></div><button className="mhl-icon" aria-label={sound?t(locale,'mute'):t(locale,'unmute')} onPointerDown={()=>setSound(v=>!v)}><SoundIcon off={!sound}/></button></header>
 {phase==='cover'&&<section className="mhl-cover"><div className="mhl-cover__plaque"><span>EST. 1927</span><b>THE AUBERGE<br/>NOCTURNE</b><i>GRAND HOTEL</i></div><div className="mhl-cover__window"><img src="./generated/hotel_start.webp" alt="Mara and the guest in room 307" draggable={false}/><span>ROOM 307</span><strong>02:17 AM</strong></div><p>{t(locale,'subtitle')}</p><button className="mhl-primary" onPointerDown={boot}><span>{t(locale,'start')}</span><ArrowIcon/></button><div className="mhl-cover__keys"><i/><i/><i/><i/><i/></div></section>}
 {phase==='incident'&&<section className="mhl-incident"><div className="mhl-casebar"><span>{t(locale,'case')}</span><strong>{t(locale,'time')}</strong></div><h2>{t(locale,'question')}</h2><HotelStill locale={locale}/><p className="mhl-instruction">{t(locale,'choose')}</p><div className="mhl-options">{endings.map(e=><button key={e.id} onPointerDown={()=>select(e.id)}><span>{e.code}</span><strong>{e.label[locale]}</strong><i>{found.has(e.id)?'FILED':'OPEN'}</i></button>)}</div></section>}
 {(phase==='footage'||phase==='report')&&selected&&item&&<section className="mhl-play"><div className="mhl-reelbar"><span>{phase==='footage'?t(locale,'live'):t(locale,'report')}</span><strong>{item.code} · {item.label[locale]}</strong></div><Footage id={selected} beat={beat} locale={locale} result={phase==='report'}/>{phase==='report'&&<div className="mhl-report"><div><span>{t(locale,isNew?'new':'seen')}</span><b>{found.size}/3</b></div><h2>{item.title[locale]}</h2><p>{item.detail[locale]}</p>{found.size===3&&<strong className="mhl-report__sealed">{t(locale,'sealed')}</strong>}<button className="mhl-primary" onPointerDown={review}><span>{t(locale,'review')}</span><ArrowIcon/></button></div>}</section>}
 <footer><span>CONFIDENTIAL NIGHT RECORD</span><img src="./alteru.svg" alt="AlterU" draggable={false}/><span>LEDGER · 307</span></footer></article></main>}
